# this is the travis buidl script recommendation from jekyllrb.com
# see https://jekyllrb.com/docs/continuous-integration/travis-ci/
language: ruby
rvm:
- 2.3.3

# since we directly call install and script, we do not need a
# before_script:
#  - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install: gem install jekyll html-proofer
script: jekyll build


# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
